dist:
  name: otelcol-cloudflare-logs
  description: Basic OTel Collector distribution for Cloudflare Logs
  output_path: ./otelcol-cloudflare

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.120.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.120.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.120.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/cloudflarereceiver v0.120.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
