name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OCB_VERSION=0.20.0

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenTelemetry Collector Builder
        run: curl --proto '=https' --tlsv1.2 -fL -o /usr/local/bin/ocb https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv$OCB_VERSION/ocb_$OCB_VERSION_linux_amd64 && chmod +x /usr/local/bin/ocb          
