name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OCB_VERSION: '0.120.0'

    steps:
      - uses: actions/checkout@v4

      - name: Install OTel Collector Builder
        run: curl --proto '=https' --tlsv1.2 -fL -o /usr/local/bin/ocb https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv${OCB_VERSION}/ocb_${OCB_VERSION}_linux_amd64 && chmod +x /usr/local/bin/ocb          

      - name: Build OTel Collector
        run: ocb --config src/cloudflare-receiver/builder-config.yaml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

