name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'distributions/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: sboschman/otel-collector-distributions/.github/actions/build-action@main
        name: Build
