name: Build

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'Dockerfile'
    #   - 'go.mod'
    #   - 'go.sum'
    #   - 'distributions/**'
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: sboschman/otel-collector-distributions/.github/actions/build-action@main
        name: Build
        
      # - uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get Go version
      #   run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV

      # - name: Build and push image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./distributions/otelcol-cloudflare
      #     build-contexts: |
      #       ocb=.
      #     file: ./Dockerfile
      #     build-args: |
      #       GO_VERSION=${{ env.GO_VERSION }}
      #     platforms: "linux/arm64,linux/amd64"
      #     labels: |
      #       org.opencontainers.image.source=https://github.com/{{ github.repository }}
      #       org.opencontainers.image.created={{.Date}}
      #       org.opencontainers.image.title={{.ProjectName}}
      #       org.opencontainers.image.revision={{.FullCommit}}
      #       org.opencontainers.image.version={{.Version}}
      #       org.opencontainers.image.description=OTel Collector - Cloudflare Logs
      #     push: true
      #     outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=OTel Collector - Cloudflare Logs
      #     tags: ghcr.io/${{ github.actor }}/opentelemetry-collector-cloudflare:latest
