name: build and optionally publish to ci registry

on:
  workflow_call:
    inputs:
      path:
        description: OTel Collector path
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build-push:
    runs-on: "ubuntu-latest"
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: ${{ github.event_name == 'pull_request' && 1 || 2 }}
            # ref: ${{ inputs.git_tag_name || '' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    #   - name: Login to GitHub Container Registry
    #     uses: docker/login-action@v3
    #     if: ${{ inputs.publish == 'true' }}
    #     with:
    #         registry: ghcr.io
    #         username: ${{ github.actor }}
    #         password: ${{ inputs.token }}

      - name: Get Go version
        run: |
          echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV
          echo "Detected: $GITHUB_ENV.GO_VERSION"

      - name: Get metadata from manifest
        run: |
          echo "OTEL_NAME=$(yq '.dist.name'${{ inputs.path }}/manifest.yaml)" >> $GITHUB_ENV
          echo "OTEL_DESCRIPTION=$(yq '.dist.description' ${{ inputs.path }}/manifest.yaml)" >> $GITHUB_ENV
          echo "OTEL_IMAGE_NAME=${GITHUB_ENV.OTEL_NAME/otelcol/opentelemetry-collector}" >> $GITHUB_ENV
          echo "$GITHUB_ENV.OTEL_NAME"
          echo "$GITHUB_ENV.OTEL_DESCRIPTION"
          echo "$GITHUB_ENV.OTEL_IMAGE_NAME"
          env
          echo $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.path }}
          build-contexts: |
            ocb=.
            file: ./Dockerfile
            build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            platforms: "linux/arm64,linux/amd64"
            labels: |
            org.opencontainers.image.source=https://github.com/{{ github.repository }}
            org.opencontainers.image.created={{.Date}}
            org.opencontainers.image.title={{.ProjectName}}
            org.opencontainers.image.revision={{.FullCommit}}
            org.opencontainers.image.version={{.Version}}
            org.opencontainers.image.description=${{ env.OTEL_DESCRIPTION }}
            push: ${{ inputs.publish == 'true' }}
            outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=${{ env.OTEL_DESCRIPTION }}
            tags: ghcr.io/${{ github.actor }}/${{ env.OTEL_IMAGE_NAME }}:latest
