name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OTEL_VERSION: '0.120.0'

    steps:
      - uses: actions/checkout@v4

      # - name: Install OTel Collector Builder
      #   run: curl --proto '=https' --tlsv1.2 -fL -o /usr/local/bin/ocb https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv${OCB_VERSION}/ocb_${OCB_VERSION}_linux_amd64 && chmod +x /usr/local/bin/ocb          

      # - name: Build OTel Collector
      #   run: ocb --config src/cloudflare-receiver/builder-config.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            OTEL_VERSION=${{env.OTEL_VERSION}}
          platforms: "linux/arm64,linux/amd64"
          labels: |
            org.opencontainers.image.source=https://github.com/{{ github.repository }}
            org.opencontainers.image.created={{.Date}}
            org.opencontainers.image.title={{.ProjectName}}
            org.opencontainers.image.revision={{.FullCommit}}
            org.opencontainers.image.version={{.Version}}
            org.opencontainers.image.description=OTel Collector - Cloudflare Logs
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=OTel Collector - Cloudflare Logs
          tags: ghcr.io/${{ github.actor }}/opentelemetry-collector-cloudflare:latest
