name: release
on:
  push:
    tags:
      - 'otelcol-*-v*'

permissions:
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: sboschman/otel-collector-distributions/.github/actions/build-action@main
        name: Publish
        with:
          publish: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
