name: Release

on:
  repository_dispatch:
    types: [publish-assets]

permissions:
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload }}
      # - uses: sboschman/otel-collector-distributions/.github/actions/build-action@main
      #   name: Publish
      #   with:
      #     publish: 'true'
      #     token: ${{ secrets.GITHUB_TOKEN }}
